html_document:
  self_contained: no
  lib_dir: ../html/libs
  code_download: no
  code_folding: show
  css:
    - ../html/css/vue.css
    - ../html/css/vue.user.css
  fig_caption: yes
  theme: united
  highlight: haddock
  number_sections: no
  toc: yes
  toc_depth: 4
  toc_float:
    collapsed: yes
    smooth_scroll: yes
