---
title: "Ones and Zeros"
author: "Humoon"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include = FALSE}
source("./config/config.R")

## global options ===================================
knitr::opts_chunk$set(
  width = config$width,
  fig.width = config$fig.width,
  fig.asp = config$fig.asp,
  out.width = config$out.width,
  fig.align = config$fig.align,
  fig.path = config$fig.path,
  fig.show = config$fig.show,
  warn = config$warn,
  warning = config$warning,
  message = config$message,
  echo = config$echo,
  eval = config$eval,
  tidy = config$tidy,
  comment = config$comment,
  collapse = config$collapse,
  cache = config$cache,
  cache.comments = config$cache.comments,
  autodep = config$autodep
)
```



### Description


Given an array of ones and zeroes, convert the equivalent binary value to an integer.

Eg: `[0, 0, 0, 1]` is treated as `0001` which is the binary representation of `1`.

#### Examples

```
Testing: [0, 0, 0, 1] ==> 1
Testing: [0, 0, 1, 0] ==> 2
Testing: [0, 1, 0, 1] ==> 5
Testing: [1, 0, 0, 1] ==> 9
Testing: [0, 0, 1, 0] ==> 2
Testing: [0, 1, 1, 0] ==> 6
Testing: [1, 1, 1, 1] ==> 15
Testing: [1, 0, 1, 1] ==> 11
```

However, the arrays can have varying lengths, not just limited to `4`.


### Solution

#### R
```{r}
library(tidyverse)

binary2number <- function(arr) {
  # 向量化操作
  # map2_dbl(
  #   .x = rev(arr),
  #   .y = 0:(length(arr) - 1),
  #   .f = function(x, i) x * 2^i
  # ) %>% sum()

  # 转换 k 进制字符串为 10 进制整数
  str_c(arr, collapse = "") %>% strtoi(base = 2L)
}

library(testthat)
test_that("Sample Tests", {
  expect_equal(binary2number(c(0, 1, 1, 0)), 6)
})
```


#### Julia
```{julia}

function binaryarraytonumber(arr)
  # 解法一：二元函数 (i, x) 的向量化操作
  # [x * 2^(i - 1) for (i, x) ∈ enumerate(reverse(arr))] |> sum

  # 解法二：解析二进制字符串为10进制整数
  parse(Int, join(arr), base=2)
end

using Test
@test binaryarraytonumber([0, 1, 1, 0]) == 6
```


#### JavaScript

```{node}
const sum = require("../../src/JavaScript/toolkit/Statistics").sum;


const binaryArrayToNumber = arr => {
  // 向量化操作
  // return sum(arr.reverse().map((x, i) => x * Math.pow(2, i)));

  // 解析2进制字符串为10进制整数
  return parseInt(arr.join(''), 2);
};


console.log(binaryArrayToNumber([0, 1, 1, 0]) == 6);
```


