---
title: "Pyramid Array"
author: "Humoon"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include = FALSE}
source("./config/config.R")

## global options ===================================
knitr::opts_chunk$set(
  width = config$width,
  fig.width = config$fig.width,
  fig.asp = config$fig.asp,
  out.width = config$out.width,
  fig.align = config$fig.align,
  fig.path = config$fig.path,
  fig.show = config$fig.show,
  warn = config$warn,
  warning = config$warning,
  message = config$message,
  echo = config$echo,
  eval = config$eval,
  tidy = config$tidy,
  comment = config$comment,
  collapse = config$collapse,
  cache = config$cache,
  cache.comments = config$cache.comments,
  autodep = config$autodep
)
```



### Description

Write a function that when given a number >= 0, returns an Array of ascending length subarrays.

```
pyramid(0) => [ ]
pyramid(1) => [ [1] ]
pyramid(2) => [ [1], [1, 1] ]
pyramid(3) => [ [1], [1, 1], [1, 1, 1] ]
```

Note: the subarrays should be filled with 1s


### Solution

#### R
```{r}
library(tidyverse)

pyramid <- function(n) {
  1:n %>% map(~ rep(1, .x))
}

pyramid(3)
```


#### Julia
```{julia}
function pyramid(n)
  # 等价的三种写法
  # [ones(Int, k) for k ∈ 1:n]
  # [fill(1, k) for k ∈ 1:n]
  [repeat([1], k) for k ∈ 1:n]
end

using Test
@test pyramid(3) == [[1], [1, 1], [1, 1, 1]]
```


#### JavaScript

```{node}
/**
 * @module Pyramid-Array
 * @file JS 中的 repeat 可以考虑 Array(n).fill()
 */

const repeat = require("../../src/JavaScript/toolkit/Vector").repeat;

function pyramid(n) {
  return [...Array(n)].map((_, i) => repeat([1], i + 1));
}

console.log(pyramid(3));
```


