---
title: "Split Strings"
author: "Humoon"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include = FALSE}
source("./config/config.R")

## global options ===================================
knitr::opts_chunk$set(
  width = config$width,
  fig.width = config$fig.width,
  fig.asp = config$fig.asp,
  out.width = config$out.width,
  fig.align = config$fig.align,
  fig.path = config$fig.path,
  fig.show = config$fig.show,
  warn = config$warn,
  warning = config$warning,
  message = config$message,
  echo = config$echo,
  eval = config$eval,
  tidy = config$tidy,
  comment = config$comment,
  collapse = config$collapse,
  cache = config$cache,
  cache.comments = config$cache.comments,
  autodep = config$autodep
)
```



### Description

Complete the solution so that it splits the string into pairs of two characters. If the string contains an odd number of characters then it should replace the missing second character of the final pair with an underscore ('_').

#### Examples

```
* 'abc' =>  ['ab', 'c_']
* 'abcdef' => ['ab', 'cd', 'ef']
```


### Solution

#### R
```{r}
library(tidyverse)
library(magrittr)

solution <- function(string) {
  string %>%
    str_c("_") %>%
    str_extract_all(".{2}") %>%
    extract2(1)
}

library(testthat)
test_that("Sample Tests", {
  expect_equal(solution("abc"), c("ab", "c_"))
  expect_equal(solution("abcd"), c("ab", "cd"))
})
```


#### JavaScript

```{node}


function solution(str) {
    // 解法一：遍历字符的 index
    // const n = str.length;
    // let array = [];
    // if (n % 2 === 1) {
    //   str += '_';
    // }
    // for (let i = 0; i < n / 2; i++) {
    //   array.push(str.slice(2 * i, 2 * i + 2));
    // }
    // return array;

    // 解法二：string.match() 正则匹配
    // str 为 '' 时，匹配失败返回 null，对应的布尔值为 flase
    // 短路逻辑，返回第一个布尔值为 true 的初始值，即[]
    return (str + "_").match(/.{2}/g) || [];
    // 等价于
    // if (str === '') {
    //   return [];
    // } else {
    //   return (str + "_").match(/.{2}/g);
    // }
}


module.exports = solution;
```


